my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: admin
      dbname: bitcoin_engine
      schema: public 